#pragma once
#define POINTING_DEVICE_ROTATION_270
#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_LGUI_SWAP
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define SPLITTHINGHERE true
#define DEFAULT_JOYSTICK_SPEED 2
